CREATE TABLE `model` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增id',
  `time` varchar(10) NOT NULL DEFAULT '' COMMENT '来源',
  `negprecision` float NOT NULL DEFAULT '0' COMMENT '成功次数',
  `negrecall` float NOT NULL DEFAULT '0' COMMENT '成功次数',
  `negf1score` float NOT NULL DEFAULT '0' COMMENT '成功次数',
  `negpsupport` int(12) NOT NULL DEFAULT '0' COMMENT '成功次数',
  `posprecision` float NOT NULL DEFAULT '0' COMMENT '成功次数',
  `posrecall` float NOT NULL DEFAULT '0' COMMENT '成功次数',
  `posf1score` float NOT NULL DEFAULT '0' COMMENT '成功次数',
  `pospsupport` int(12) NOT NULL DEFAULT '0' COMMENT '成功次数',
  `allprecision` float NOT NULL DEFAULT '0' COMMENT '成功次数',
  `allrecall` float NOT NULL DEFAULT '0' COMMENT '成功次数',
  `allf1score` float NOT NULL DEFAULT '0' COMMENT '成功次数',
  `allpsupport` int(12) NOT NULL DEFAULT '0' COMMENT '成功次数',
  `num` int(11) unsigned NOT NULL,
  `auc` float unsigned NOT NULL,
  `name` varchar(30) NOT NULL DEFAULT '',
  `type` varchar(30) NOT NULL DEFAULT '',
  `zhengPersent` float NOT NULL DEFAULT '0',
  `note` varchar(100) NOT NULL DEFAULT '',
  `filename` varchar(100) NOT NULL DEFAULT '',
  `accuracy` float NOT NULL DEFAULT '0',
  `threshold` float NOT NULL,
  `modelName` varchar(10) NOT NULL DEFAULT '模型名称',
  `Conf_c` varchar(10) NOT NULL DEFAULT '正则化强度',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=361 DEFAULT CHARSET=utf8 COMMENT='TP表'